# -*- coding:utf-8 -*-
# this is auto-generated by swagger-marshmallow-codegen
from swagger_marshmallow_codegen.schema.legacy import LegacySchema
from marshmallow import fields


class Person(LegacySchema):
    name = fields.String(required=True)
    age = fields.Integer()
