# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
    INCLUDE,
)
from .Pet import Pet
from swagger_marshmallow_codegen.validate import Range


class Dog(Pet):
    """A representation of a dog"""
    packSize = fields.Integer(required=True, description='the size of the pack the dog is from', validate=[Range(min=0, max=None, min_inclusive=True, max_inclusive=True)])

    class Meta:
        unknown = INCLUDE
