# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
    INCLUDE,
)
from .Shop import Shop


class Pet(Schema):
    id = fields.Integer(required=True)
    name = fields.String(required=True)
    shop = fields.Nested(lambda: Shop())
    father = fields.Nested(lambda: Pet())
    mother = fields.Nested(lambda: Pet())
    tag = fields.String()

    class Meta:
        unknown = INCLUDE
