# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
    INCLUDE,
)


class Shop(Schema):
    id = fields.Integer(required=True)
    name = fields.String(required=True)

    class Meta:
        unknown = INCLUDE
