# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
    INCLUDE,
)


class ShopDescription(Schema):
    content = fields.String()
    position = fields.String()

    class Meta:
        unknown = INCLUDE
