# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
    INCLUDE,
)


class Error(Schema):
    code = fields.Integer(required=True)
    message = fields.String(required=True)

    class Meta:
        unknown = INCLUDE
