# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
    INCLUDE,
)


class Pet(Schema):
    id = fields.Integer(required=True)
    name = fields.String(required=True)
    tag = fields.String()

    class Meta:
        unknown = INCLUDE
