language: python
sudo: false
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"
install:
  - pip install -e .[testing]
  - pip install bson
script:
  - python setup.py test
  - make ci
