# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from swagger_marshmallow_codegen.schema.legacy import (
    LegacySchema,
    PrimitiveValueSchema,
)
from marshmallow import fields


class IdsInput:
    class Get:
        pass



class IdsIdInput:
    class Get:
        pass



class IdsOutput:
    class Get200(PrimitiveValueSchema):
        class schema_class(LegacySchema):
            value = fields.List(fields.Integer())




class IdsIdOutput:
    class Get200(PrimitiveValueSchema):
        class schema_class(LegacySchema):
            value = fields.Integer()
