# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
    INCLUDE,
)


class Team(Schema):
    members = fields.List(fields.Nested(lambda: User()))
    name = fields.String()

    class Meta:
        unknown = INCLUDE
