# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
    INCLUDE,
)


class User(Schema):
    name = fields.String()
    team = fields.Nested(lambda: Team())

    class Meta:
        unknown = INCLUDE
