# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
    INCLUDE,
)
from ._lazy import _useTeam


class User(Schema):
    name = fields.String()
    team = fields.Nested(_useTeam)

    class Meta:
        unknown = INCLUDE
