# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
    INCLUDE,
)
from marshmallow.validate import OneOf


class Error(Schema):
    code = fields.Integer(required=True)
    message = fields.String(required=True)
    categoris = fields.List(fields.String(validate=[OneOf(choices=['API', 'Internal', 'Bug', 'Human'], labels=[])]))

    class Meta:
        unknown = INCLUDE
