# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
    INCLUDE,
)
import re
from marshmallow.validate import Regexp
from .Id import Id


class Pet(Schema):
    father = fields.Nested(lambda: Pet())
    id = fields.String(required=True, description='ObjectId', validate=[Regexp(regex=re.compile('[0-9a-f]{24}'))])
    mother = fields.Nested(lambda: Pet())
    name = fields.String(required=True)
    shop = fields.Nested(lambda: Shop())
    tag = fields.String()

    class Meta:
        unknown = INCLUDE
