# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
    INCLUDE,
)
import re
from marshmallow.validate import Regexp


class Shop(Schema):
    id = fields.String(required=True, description='ObjectId', validate=[Regexp(regex=re.compile('[0-9a-f]{24}'))])
    name = fields.String(required=True)
    description = fields.Nested(lambda: ShopDescription())

    class Meta:
        unknown = INCLUDE



class ShopDescription(Schema):
    content = fields.String()
    position = fields.String()

    class Meta:
        unknown = INCLUDE
